### ISSUE TITLE
DeltaTime Extension

### ISSUE THREAD

**Issue by IXLLEGACYIXL** [VaclavElias/stride-community-toolkit#13]
As its tedious and hard to find as new commer, from Unity or Godot, the DeltaTime i made this extension to make it easier accessible

Motivation:
godot changed their delta time to double
`public override void _Process(double delta)`
the Community got mad as you need to convert each time the double to float to be able to use it with Vectors

with this extension you are able to have easy access to delta and having it as double and float available

```cs
public static class DeltaExtension
{
    public static float DeltaTime(this IGame gameTime)
    {
        return (float)gameTime.UpdateTime.Elapsed.TotalSeconds;
    }
    public static double DeltaTimeAccurate(this IGame gameTime)
    {
        return gameTime.UpdateTime.Elapsed.TotalSeconds;
    }
}
```
usage looks like this in a sync script
![grafik](https://github.com/VaclavElias/stride-code-only/assets/107197024/364bfbe7-d6f1-49db-9176-91920680306f)

**Comment by IXLLEGACYIXL** [comment]
https://github.com/NexStandard/NexCoreExtension/blob/main/DeltaExtension.cs

For Reference

**Comment by IXLLEGACYIXL** [comment]
solved with merge of nexcore extension

**Comment by VaclavElias** [comment]
Thank you
