### ISSUE TITLE
GameWindow has no GetSize but a SetSize

### ISSUE THREAD

**Issue by IXLLEGACYIXL** [VaclavElias/stride-community-toolkit#14]
as i have no clue where to actually get the size of a window i wrote this, idk if its correct or accurate 
I just tried to get somehow the height and width of the current window

```
public static class GameWindowSizeExtension
{
    public static Int2 GetWindowSize(this GraphicsDevice graphics)
    {
        int width = graphics.Presenter.BackBuffer.Width;
        int height = graphics.Presenter.BackBuffer.Height;
        return new Int2(width, height);
    }
}
```

**Comment by IXLLEGACYIXL** [comment]
https://github.com/NexStandard/NexCoreExtension/blob/main/GameWindowSizeExtension.cs

For Reference

**Comment by IXLLEGACYIXL** [comment]
was fixed with merge of nexcore extensions

**Comment by VaclavElias** [comment]
Thank you
